### ISSUE TITLE
Module not find

### ISSUE THREAD

**Issue by powersoft** [AustL/PygameWidgets#11]
Hello,

Installed pygame_widgets, and get the next error.
Please can you help me out

pygame 2.0.0.dev8 (SDL 2.0.12, python 3.8.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "Untitled.py", line 2, in <module>
    import pygame_widgets
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pygame_widgets/__init__.py", line 4, in <module>
    from pygame_widgets.animations.animation import AnimationBase, Translate, Resize
ModuleNotFoundError: No module named 'pygame_widgets.animations'

**Comment by AustL** [comment]
Forgot to put an __init__.py file inside the sub-directories. Fixed now, thanks.
