### ISSUE TITLE
animation example has importError

### ISSUE THREAD

**Issue by zitot** [AustL/PygameWidgets#68]
https://pygamewidgets.readthedocs.io/en/latest/animations/animations/

```py
import pygame_widgets
import pygame
from pygame_widgets.button import Button
from pygame_widgets.animations import Resize

pygame.init()
win = pygame.display.set_mode((600, 600))

button = Button(win, 100, 100, 300, 150)

animation = Resize(button, 3, 200, 200)
animation.start()

run = True
while run:
    events = pygame.event.get()
    for event in events:
        if event.type == pygame.QUIT:
            pygame.quit()
            run = False
            quit()

    win.fill((255, 255, 255))

    pygame_widgets.update(events)
    pygame.display.update()
```

```
Traceback (most recent call last):                                                     
  File "C:\Users\zitot\Documents\ICS211\pygame-widget\animation.py", line 4, in <module>                                                                                      
    from pygame_widgets.animations import Resize                                       
  File "C:\Users\zitot\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygame_widgets\animations\__init__.py", line 1, in <module>                                  
    from animation import Resize, Recolour, Translate                                  
  File "C:\Users\zitot\Documents\ICS211\pygame-widget\animation.py", line 4, in <module>                                                                                      
    from pygame_widgets.animations import Resize                                       
ImportError: cannot import name 'Resize' from partially initialized module 'pygame_widgets.animations' (most likely due to a circular import) (C:\Users\zitot\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygame_widgets\animations\__init__.py)       

```

**Comment by AustL** [comment]
Resoleved
